### ISSUE TITLE
Allowing ingress annotations for auto-generating valid certificates

### ISSUE THREAD

**Issue by UnicornyRainbow** [kasmtech/kasm-helm#14]
At the moment it is only possible to generate self-signed certificates in the helm chart or manually deploying your own.
It would be nice to be able to specify annotations for the ingresses as this is used by cert-manager (and maybe others?) to generate certificates.
Most helm charts have a `ingress.anotations: {}` option for each ingress.
Here it could lokk something like:
```yaml
## @param kasmCerts.ingress.name Name used for Kasm Ingres Certificate Secret (if resource already exists, use resource name here and set create = false)
## @param kasmCerts.ingress.annotations add annotations to the ingress
## @param kasmCerts.ingress.create true/false used to create the Ingress resource
## @param kasmCerts.ingress.cert Add externally-generated Intress TLS Public certificate
## @param kasmCerts.ingress.key Add externally-generated Intress TLS Private key
##
ingress:
  name: kasm-ingress-cert
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    cert-manager.io/common-name: kasm.example.com
    cert-manager.io/private-key-algorithm: ECDSA
    cert-manager.io/private-key-rotation-policy: Always
    cert-manager.io/private-key-size: '384'
  create: false
  cert: |-
    ######    Place public SSL Cert here     ######
    ######  Leave empty for Helm to generate ######
  key: |-
    ######    Place public SSL Key here      ######
    ######  Leave empty for Helm to generate ######
```

Additionally ingress annotations could be useful for adding additional configuration to the ingress provider if desired, as this method of configuration is used by traefik, nginx and probably others
