### ISSUE TITLE
Air gapped not supported

### ISSUE THREAD

**Issue by floreseo2** [kasmtech/kasm-helm#18]
Since there are image that are hardcodec we can't deploy on a  air gapped enviroment.
I worked on be able to configure all images with variables on https://github.com/floreseo2/kasm-helm

**Comment by bscarbrough** [comment]
@floreseo2, thanks for this, but if you take a look at the `values.yaml` file and scroll down to the `kasmApp:` block you'll see there all of the different image definitions we're using. You'll see multiple values listed there that you are free to modify as you have a need. For the `image:` value if you're using something besides Docker hub, you'll just need to set this to the full registry/container image path.


```
    kasmProxy:
      name: kasm-proxy
      addHealthChecks: true
      image: kasmweb/proxy    # Change this value to your mirrored image
      tag: 1.17.0                    # If you changed the tag in your mirror, then change this value
      replicas: null
      serviceKeepalive: 16
```
